### ISSUE TITLE
Some images, might be duplicates.

### ISSUE THREAD

**Issue by ghost** [The-Alpha-Project/Alpha-Project-Archive#1]
[AlphaBeta02.zip](https://github.com/The-Alpha-Project/Alpha-Project-Archive/files/5586282/AlphaBeta02.zip)
[AlphaBeta01.zip](https://github.com/The-Alpha-Project/Alpha-Project-Archive/files/5586285/AlphaBeta01.zip)
[AlphaBeta03.zip](https://github.com/The-Alpha-Project/Alpha-Project-Archive/files/5586286/AlphaBeta03.zip)

**Comment by GrenderG** [comment]
Thanks for your contribution, gonna take a look!

**Comment by Daribon** [comment]
On first glance, seems to be many duplicates. 
I will look deeper into it once I have removed all current duplicates in the sorted archive.

**Comment by Daribon** [comment]
This can now be closed, I've looked through every screenshot and added what was not duplicates.
